### ISSUE TITLE
Rstr (beta) disappears from list of delegates

### ISSUE THREAD

**Issue by lex-ikoon** [stkrake/hdRstr#1]
Hello, the renderer looks really awesome! I wanted to give it a try, I edited the ENV file. But once I choose Rstr (beta) from the list of renderers, that option disappears from that list (and goes back to default Houdini GL renderer). Might this be due to the version of Houdini I am using? I tried 18.5.408 and 18.5.499. I have a Nvidia RTX card and studio drivers 471.68

Nothing gets printed in the Console or Python Shell pane. I found no log here:
C:\Users\....\AppData\Local\Temp\houdini_temp

**Comment by stkrake** [comment]
At least 18.5.499 should work, I just verified it.
The disappearing Rstr-entry typically means than the DLL could not be loaded.

Could you please add these two additional lines to your houdini.env:

TF_DEBUG = TF_DLOPEN PLUG_*
HDRSTR_LOG_LEVEL_STDERR = 0

This should log a lot of stuff into the console. And hopefully the error, too.
The first one is standard USD debugging. It basically logs what the plugin loader is doing. This should show if the dll is found at all.
The second one sets hdRstr to the highest log level and may show why the dll does not work (once it is found and loaded).

Thanks for testing.

**Comment by stkrake** [comment]
I think, I found the problem: hdRstr ist linked against python2.7 libs. If you happen to run a houdini-py3-* version the DLL is
not loaded. I will upload an additional py3-build tomorrow.

**Comment by lex-ikoon** [comment]
Thank you for your message. Yes I am on Py3. I did not yet manage to set the debugging but I will do it asap for further testing. Thanks a lot!

**Comment by stkrake** [comment]
I opened #2 for this

**Comment by stkrake** [comment]
I updated the latest release with a py3-build:
https://github.com/stkrake/hdRstr/releases/download/v0.1.3-beta/hdRstr_v013beta_hou185_py3.zip
Runs also with py3-18.5.408

**Comment by lex-ikoon** [comment]
Thank you very much, it works now! I will experiment some more :)
