### ISSUE TITLE
hdRstr does not work with maya-usd 0.13.0 (was: Entry Point Not Found)

### ISSUE THREAD

**Issue by adro79** [stkrake/hdRstr#3]
I'm using mayausd 0.13 and hdRstr v107
![image](https://user-images.githubusercontent.com/57686179/138946135-8a9a4554-2ade-482f-9474-2c629f59950f.png)

**Comment by stkrake** [comment]
maya-usd 0.15.0 [should fix this](https://github.com/Autodesk/maya-usd/issues/1741#issuecomment-979507730)  much better than my workaround.
